const model_list = [
  {"resourceName": "食品箱拍照"},
  {"resourceName": "确认箱况"},
  {"resourceName": "验箱"},
  {"resourceName": "状态更改"},
  {"resourceName": "单柜查询"},
  {"resourceName": "维修派工"},
  {"resourceName": "PTI完成"},
  {"resourceName": "权限管理"},
  {"resourceName": "污箱拍照"},
  {"resourceName": "出场拍照"},
  {"resourceName": "起租拍照"},
  {"resourceName": "监管操作"},
  {"resourceName": "监管查询"},
  {"resourceName": "监管箱查询"},
  {"resourceName": "增加估价"},
  {"resourceName": "冷箱验箱"},
  {"resourceName": "租箱验箱"},
  {"resourceName": "冷箱单柜查询"},
  {"resourceName": "冷箱状态更改"},
  {"resourceName": "冷箱维修派工"},
  {"resourceName": "冷箱增加估价"},
  {"resourceName": "冷箱机组维修"},
  {"resourceName": "保修拍照"},
];
